// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qiulin/kratos-boot/boot"
	"github.com/qiulin/kratos-boot/console"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *boot.Bootstrap) (*console.CommandLine, func(), error) {
	option := NewConsoleOption()
	confBootstrap := ExportConfig(bootstrap)
	server := NewHTTPServer(confBootstrap)
	v := NewServers(server)
	waitGroup := console.NewWaitGroup()
	app := console.NewApp(bootstrap, v, waitGroup)
	helloCommand := NewHelloCommand()
	timestampCommand := NewTimestampCommand()
	v2 := NewCommands(helloCommand, timestampCommand)
	commandLine := console.NewCommandLine(option, app, v2, waitGroup)
	return commandLine, func() {
	}, nil
}
